name: "🙋 Pull Request"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  development:
    name: Development
    uses: remix-austin/remixaustin-com/.github/workflows/development.yml@main
